cargo-features = ["edition2021"]

[package]
name = "redisjson"
version = "99.99.99"
authors = ["Guy Korland <guy.korland@redis.com>", "Meir Shpilraien <meir@redis.com>", "Omer Shadmi <omer.shadmi@redis.com>"]
edition = "2021"
description = "JSON data type for Redis"
repository = "https://github.com/RedisJSON/RedisJSON"
readme = "README.md" 
license = "Redis Source Available License (RSAL)"
keywords = ["redis", "json", "plugin"]
categories = ["database-implementations"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "rejson"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
bitflags = "1.3"
log = "0.4"
bson = "0.14"
ijson = "0.1.3"
serde_json = "1.0"
serde = "1.0"
libc = "0.2"
redis-module = { version="1.0", features = ["experimental-api"]}
itertools = "0.10"
[features]
# Workaround to allow cfg(feature = "test") in redismodue-rs dependencies:
# https://github.com/RedisLabsModules/redismodule-rs/pull/68
# This requires running the tests with `--features test`
test = ["redis-module/test"]
as-library = []

[[test]]
name = "array_filter"
path = "tests/rust_tests/array_filter.rs"

[[test]]
name = "filter"
path = "tests/rust_tests/filter.rs"

[[test]]
name = "jsonpath_examples"
path = "tests/rust_tests/jsonpath_examples.rs"

[[test]]
name = "op"
path = "tests/rust_tests/op.rs"

[[test]]
name = "paths"
path = "tests/rust_tests/paths.rs"

[[test]]
name = "return_type"
path = "tests/rust_tests/return_type.rs"

[profile.release]
debug = 1
